name:                music
version:             1.0.0.0
license:             BSD3
author:              "N Miya Sylvester"
maintainer:          "nmiya.sylvester@gmail.com"

description:
  Music generator

default-extensions:
- NoImplicitPrelude
- GADTs
- RankNTypes
- DeriveFunctor
- DeriveGeneric
- OverloadedStrings
- LambdaCase
- MultiParamTypeClasses
- ExplicitNamespaces
- TypeApplications
- ScopedTypeVariables
- TypeOperators
- TypeFamilies
- DataKinds
- FlexibleContexts
- FlexibleInstances
- PatternSynonyms
- PolyKinds
- DefaultSignatures
- ConstraintKinds
- NamedFieldPuns
- TupleSections
- ViewPatterns
- MultiWayIf
- RecordWildCards

dependencies:
- base >= 4.7 && < 5
- bytestring
- time-units
- mtl
- base16-bytestring
- base58-bytestring
- base64-bytestring
- directory
- filepath
- process
- extra
- time
- clock
- containers
- random
- free
- transformers
- text
- bytestring-conversion
- stm
- MonadRandom
- entropy
- binary
- hydra-base
- hydra-free
- csound-expression

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -fhide-source-paths

executables:
  music:
    main:                Main.hs
    source-dirs:         src/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    # - -O2
