resolver: lts-14.4

packages:
- .

extra-deps:
  - git: https://github.com/graninas/Hydra.git
    commit: 58de96d5729fed9e73a12b00551f7882e515951d
    subdirs:
      - lib/hydra-base
      - lib/hydra-free

  - base58-bytestring-0.1.0
  - time-units-1.0.0
  - rocksdb-haskell-1.0.1
